# Jekyll config
sass:
  style: compact # possible values: nested expanded compact compressed
permalink: /blog/:year/:month/:title
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

